### ISSUE TITLE
data-xt-drop elements and targets logic

### ISSUE THREAD

**Issue by lamasfoker** [minimit/xtendui#32]
## Versions

beta 19

## Describe the bug

On the [docu](https://xtendui.com/components/drop) you said:
>Only when you specify elements or targets with id the query is inside document not only inside object.

But I think that always you have to search inside document and not only inside object.
My logic seems to be much simpler to remember.

**Comment by minimit** [comment]
For drop i intend all interaction components.

Doing `document` query on `elements` and `targets` may be possible but for all the demos I've to specify a unique class for elements and targets, if one uses multiple drops for example I don't like he have to make multiple names because of the `document` query..

Another idea you had is to have one `data-xt-drop` for all drops, but if someone wants to have a different drop, it's hard to filter out that drop from the defaults.

Maybe remove defaults `elements` and `targets` query and specify it in all the demos but keeping the rest like now, for clarity and seplicity. I don't like the **magic** of defaults `elements` and `targets` too.

**Comment by minimit** [comment]
released https://github.com/minimit/xtendui/releases/tag/v1.0.0-beta.20
